// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnbgbvdrnxmdtujompxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduYmdidmRybnhtZHR1am9tcHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMzgxNjQsImV4cCI6MjA1NjgxNDE2NH0.8hzfCQ_Hbu8dLAIWbUqS_zIg9ZxZ2fSq3tEMkPDoRqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);